name: MultiRobot
author: endymx
description: 多平台通讯
main: cn.endymx.multirobot.LoadClass
version: 1.2.0
softdepend: [VexView]

commands:
  getimage:
    description: 获取一个图片并显示
  reload:
    description: 重新加载插件配置文件