name: MultiRobot
author: endymx
description: 多平台通讯
main: cn.endymx.multirobot.LoadClass
version: 2.0.0
softdepend: [VexView]

commands:
  getimage:
    description: 获取一个图片并显示
  robot:
    description: QQ连接开关
  info:
    description: 发送一条信息
  reload:
    description: 重新加载插件配置文件